services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vendas-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Vendas@12345Sql"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

  localstack:
    image: localstack/localstack:3.8
    container_name: vendas-localstack
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack
    restart: unless-stopped

volumes:
  sqlserver-data:
  localstack-data:
