<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Vendas.Worker-73675cb7-657b-47c4-9281-e1f52df57aac</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="3.7.400" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vendas.Application\Vendas.Application.csproj" />
    <ProjectReference Include="..\Vendas.Infrastructure\Vendas.Infrastructure.csproj" />
  </ItemGroup>
</Project>
